### ISSUE TITLE
Example with prometheus and grafana - order

### ISSUE THREAD

**Issue by mprevide** [vernemq/vmq-operator#14]
Hi

When I try apply _vmq-operator/examples/vernemq_grafana_prometheus/_ with more then 1 vernemq pod, prometheus can't get metrics. 

Solution, rename files to: 

vernemq-service.yaml -> o_vernemq-service.yaml
vernemq-serviceAccount..yaml -> o_vernemq-serviceAccount.yaml
vernemq-serviceMonitor.yaml -> o_vernemq-serviceMonitor.yaml
vernemq-vernemq.yaml -> o_vernemq-vernemq.yaml

So, the order was correted when apply

**Comment by larshesel** [comment]
Hi, thanks for opening the issue. I'm not sure why renaming the files like this would work - if they all have the same prefix won't the order be the same? I'm sure I'm missing something here :)

**Comment by mprevide** [comment]
Hi :)
In my case prometheus could not find the vernemq pods when prometheus starts before vernemq.
Renaming only these four files, I solved my problem.
Because vernemq started before prometheus.

**Comment by larshesel** [comment]
ah, ok, make sense. Would you be interested in creating a PR for this?

**Comment by mprevide** [comment]
i'll create a PR :smiley_cat:

**Comment by dergraf** [comment]
fixed by #15
