### ISSUE TITLE
Cannot proceed with simple install

### ISSUE THREAD

**Issue by dwhiteddsoft** [vernemq/vmq-operator#31]
As directed [here](https://docs.vernemq.com/guides/vernemq-on-kubernetes#deploy-vernemq-using-the-kubernetes-operator), the output ends up being:

```text
namespace/messaging created
deployment.apps/vmq-operator created
role.rbac.authorization.k8s.io/vmq-operator created
rolebinding.rbac.authorization.k8s.io/vmq-operator created
serviceaccount/vmq-operator created
service/vernemq-k8s created
serviceaccount/vernemq-k8s created
resource mapping not found for name: "vernemqs.vernemq.com" namespace: "" from "only_vernemq/0vernemq-operator-0vernemqCustomResourceDefinition.yaml": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
ensure CRDs are installed first
resource mapping not found for name: "k8s" namespace: "messaging" from "only_vernemq/vernemq-vernemq.yaml": no matches for kind "VerneMQ" in version "vernemq.com/v1alpha1"
ensure CRDs are installed first
```

I am running AKS on Azure v1.22.11

**Comment by dwhiteddsoft** [comment]
Looks to be a dup of this [issue](https://github.com/vernemq/vmq-operator/issues/27)

**Comment by ioolkos** [comment]
@dwhiteddsoft yes, thanks; I guess we need to do a full migration at some point: https://sdk.operatorframework.io/docs/building-operators/golang/migration/
Help, of course, is always welcome.

**Comment by dwhiteddsoft** [comment]
I am trying to get it to work by hacking around a bit but I may be able to chip in. Let me get through some work items first with it and see where I am at. :-)

**Comment by dwhiteddsoft** [comment]
I find myself with some time, have forked the repo, and am looking at migration now. Hopefully something to report soon-ish :-)
